// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZwqodUvl4_nD7Y4Ex8lmIHP4iN3316zQ',
    appId: '1:737804447993:web:6229a8f374bf7f2bc3b228',
    messagingSenderId: '737804447993',
    projectId: 'ivoire-bio-axe',
    authDomain: 'ivoire-bio-axe.firebaseapp.com',
    storageBucket: 'ivoire-bio-axe.firebasestorage.app',
    measurementId: 'G-9B8630DQC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD5DgYcj-z2fecitxGsB0-cgnKwxY0GYg',
    appId: '1:737804447993:android:7a8ed36b00f0e240c3b228',
    messagingSenderId: '737804447993',
    projectId: 'ivoire-bio-axe',
    storageBucket: 'ivoire-bio-axe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnNQaB4jYvXwW7PvQmLFfVKNmAEV5HT_E',
    appId: '1:737804447993:ios:8f2ddde65bc40696c3b228',
    messagingSenderId: '737804447993',
    projectId: 'ivoire-bio-axe',
    storageBucket: 'ivoire-bio-axe.firebasestorage.app',
    iosBundleId: 'com.example.projetApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnNQaB4jYvXwW7PvQmLFfVKNmAEV5HT_E',
    appId: '1:737804447993:ios:8f2ddde65bc40696c3b228',
    messagingSenderId: '737804447993',
    projectId: 'ivoire-bio-axe',
    storageBucket: 'ivoire-bio-axe.firebasestorage.app',
    iosBundleId: 'com.example.projetApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZwqodUvl4_nD7Y4Ex8lmIHP4iN3316zQ',
    appId: '1:737804447993:web:7f91921ccf8e2d56c3b228',
    messagingSenderId: '737804447993',
    projectId: 'ivoire-bio-axe',
    authDomain: 'ivoire-bio-axe.firebaseapp.com',
    storageBucket: 'ivoire-bio-axe.firebasestorage.app',
    measurementId: 'G-QRJ0PE1WW9',
  );
}
